version: "3.9"

networks:
    laravel:
        name: laravel

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - php
            - postgres
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    # Replace mysql with postgres
    postgres:
        image: postgres:latest  # Use the latest official postgres image
        container_name: postgres
        ports:
            - 5432:5432  # Postgres default port
        environment:
            POSTGRES_DB: laraveldb  # Database name
            POSTGRES_USER: laravel  # Database user
            POSTGRES_PASSWORD: secret  # Database password
        volumes:
            - postgres-data:/var/lib/postgresql/data  # Persistent storage for postgres data

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']
        networks:
            - laravel

    npm:
        image: node:current-alpine
        container_name: npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel

# New volume for postgres data persistence
volumes:
  postgres-data:
