version: '3'

services:

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:80"

  db:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
